[versions]
# custom
applicationId = "com.vl.chepuha"
namespace = "com.fxynos.chepuha"
versionCode = "1"
versionName = "1.0"
minSdk = "27"
targetSdk = "36"
compileSdk = "36"
targetJvm = "17"

# versions
agp = "9.0.0"
kotlin = "2.0.0"
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"
hilt = "2.60"
compose = "2026.06.01"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

hilt-javax = { group = "javax.inject", name = "javax.inject", version = "1" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" } # ksp

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" } # debugImplementation

compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.13.0" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "2.11.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }

ksp = { id = "com.google.devtools.ksp", version = "2.3.6" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]
compose-implementation = [
    "compose-bom", "compose-material3", "compose-tooling-preview", "compose-activity", "compose-viewmodel"
]
compose-debug-implementation = ["compose-tooling"]