[versions]
# custom
applicationId = "com.vl.chepuha"
namespace = "com.fxynos.chepuha"
versionCode = "1"
versionName = "1.0"
minSdk = "27"
targetSdk = "36"
compileSdk = "36"
targetJvm = "17"

# versions
agp = "8.5.2"
kotlin = "2.0.0"
coreKtx = "1.16.0"
appcompat = "1.7.1"
material = "1.12.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

